### ISSUE TITLE
link to blog post is dead

### ISSUE THREAD

**Issue by ritschwumm** [tornqvist/bpm-detective#2]
the link "Beat Detection Using JavaScript and the Web Audio API" is dead - it seems tech.beatport.com does not exist

**Comment by tornqvist** [comment]
Thx, good catch! I've updated the README with a cached version of the blog post on webarchive. http://web.archive.org/web/20160401073744/http://tech.beatport.com/2014/web-audio/beat-detection-using-web-audio/

**Comment by ritschwumm** [comment]
ah, that's the same as http://joesul.li/van/beat-detection-using-web-audio/ right?

**Comment by tornqvist** [comment]
Aha, sure looks like it. I updated the readme to give credit where credit's due.
